### ISSUE TITLE
Telegra.ph or telegram url are not opening in android

### ISSUE THREAD

**Issue by arsalan123ahmed** [telegraf/telegra.ph#4]
This site can’t be reachedtelegra.ph took too long to respond.
Try:

Checking the connection
ERR_CONNECTION_TIMED_OUT
What is the problems?
Hope anyone will give solution
Thanks in advance

**Comment by GodBleak** [comment]
This is a node.js wrapper for the Telegra.ph API. That's a network issue or an issue with the Telegra.ph service itself, such issues would be beyond the scope of this project. @dotcypress, this can be closed.

**Comment by lsnnt** [comment]
i think telegra.ph servers are banned in india like other NSFW websites are banned
![image](https://github.com/telegraf/telegra.ph/assets/85880458/be38160c-42e1-42ef-8a15-842aa2c41e51)
![image](https://github.com/telegraf/telegra.ph/assets/85880458/76ec3e10-51f0-4e3a-ac9e-66db5a06331a)
So this is a censorship implemented by government of india.
And i don't know which type of censorship mechanism is implemented here because it's clearly not dnsspoofing
And i got shocked when i used a proxy server located inside india typically a vm with squid and it worked

**Comment by GodBleak** [comment]
@lsnnt Again, that has nothing to do with this repository. This is **not** the repository for [telegra.ph](https://telegra.ph). It's the repository for https://www.npmjs.com/package/telegra.ph.
